services:
  app_control_plane_pg:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.control_plane_pg
    environment:
      CONNECTION_URI: $APP_CONTROL_PLANE_PG_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_CONTROL_PLANE_PG_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_CONTROL_PLANE_PG_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_CONTROL_PLANE_PG_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8147:8080
