services:
  app_support_tickets_pg:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.support_tickets_pg
    environment:
      CONNECTION_URI: $APP_SUPPORT_TICKETS_PG_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_SUPPORT_TICKETS_PG_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_SUPPORT_TICKETS_PG_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_SUPPORT_TICKETS_PG_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4023:8080
